### ISSUE TITLE
`TypeError: 'pygame.surface.Surface' object is not callable` regardless of correct syntax

### ISSUE THREAD

**Issue by FlookyBS** [kadir014/pygame-video#5]
I'm trying to load a video using tkinter and os.path.join as mentioned, however whenever i try to do that it just errors out regardless. This is wonky behavior because i can perfectly load videos in this for loop
![image](https://github.com/kadir014/pygame-video/assets/69437909/239b8c8e-b299-450b-bab2-f508b8ecf0a7)
but not like this:
![image](https://github.com/kadir014/pygame-video/assets/69437909/768ea140-9805-4851-8542-ef85cb2d159f)
![image](https://github.com/kadir014/pygame-video/assets/69437909/34f41eb4-fde3-4267-ae84-2a8ecdba9874)

**Comment by FlookyPupper** [comment]
It never works inside of if, while and def statements, but also as I said. it does. It's wonky behavior.

**Comment by durkisneer1** [comment]
Would you happen to have a surface instance assigned to a variable named "Video"?

**Comment by FlookyPupper** [comment]
I did. Sorry.
